### PR TITLE
Fix/show robots with unknown state

### PR DESCRIPTION
**Pull request by ChawinTan**
### fixes # [related issue, if exist]

#166 

Display robots on the visualizer and the omnipanel that have been previously cached but have lost connection to the backend.

Make a temporary display for fleets that do not send signal upon initialization.

### [Describe your changes]

- Implemented a display in place of the accordion when a fleet fails to send signal upon start up
No_fleet_signal
- Implemented a display to show robots that were previously cached but have disconnected in the accordion
no_signal_accordion
one_signal_one_no
- Implemented a caching system to store new fleet, robots and update their respective state for comparison
- Robot overlay uses cachedRobots to display icons and related data instead

## Self-checks

- [x] I'm familiar with and follow this [ Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [x] I tried testing edge cases
- [x] I tested the behavior of the components that interact with the backend, with an e2e test

### [Questions for reviewers]

Right now, no icons are displayed if no robot have been cached. Should we hardcode the default starting positions of the robots in `resourceManager` in this scenario to display the icons?

Currently, when a fleet fails to send any signal from any of its robots, the omnipanel displays a message as shown in the first picture. Is this sufficient for now or should we implement something more robust, for example, if the fleet is still not returning states after 50 subscriptions, then we send an sms to the operator?

### CODE REVIEW

**Comment by ChawinTan** [comment]
Will add the stories later when things are more confirmed

**Review by koonpeng — CHANGES_REQUESTED** [review]
I would suggest to have proper backend support instead of doing client side caching. The problem with it is that each cache will have its own cache, so eventually different clients will report different robots in some scenarios, for example

1. client A starts
2. client A receives fleet state with RobotA and RobotB
3. client B starts
4. both client receive fleet state with RobotA

now client A says RobotB has unknown state, but client B says there is no such thing as RobotB. So we need a backend that can provide the "single truth" of all robots managed by rmf and their current status, we could have a server that listens to fleet states and attempts to synchronize the robot statuses based on various factors like how long since the last state received. But imo it's better if rmf can provide that information since it should have more reliable data on when robot is added/removed from the system.

**Comment by koonpeng** [comment]
converting this to a draft until the missing backend support is available.

**Comment by mxgrey** [comment]
In this context, does "backend" refer to the whole distributed RMF system, or do we anticipate a specific backend webserver application (maybe that runs on the main RMF server machine) specifically to aggregate data to send off to the dashboards?

**Pull request closed without merging**
